shallow_clone: true

environment:
  matrix:
  - LUA: "lua=5.1"
  - LUA: "lua=5.2"
  - LUA: "lua=5.3"
  - LUA: "lua=5.4"
  - LUA: "lua=5.5"
  - LUA: "luajit=2.0"
  - LUA: "luajit=2.1"

configuration:
  - vs08_32
  - vs_64
  - mingw

install:
  - set PATH=C:\Python27\Scripts;C:\MinGW\bin;%PATH%
  - pip install git+https://github.com/luarocks/hererocks
  - hererocks lua_install --%LUA% --target %configuration% -r latest
  - call lua_install\bin\activate
  - git clone --depth=1 https://github.com/lunarmodules/luacov luacov-src
  - cd luacov-src && luarocks make && cd ..
  - git clone --depth=1 https://github.com/lunarmodules/busted busted-src
  - cd busted-src && luarocks make && cd ..

build_script:
  - luarocks make --deps-mode=none

test_script:
  - busted
  - busted -C luacov
