#!/usr/bin/env bash
#
# Aggregator script: runs every e2e/*.lua scenario in sequence,
# tallies pass/fail, and exits non-zero if anything failed.
#
# Each individual e2e script is expected to:
#   - exit 0 on success
#   - exit non-zero on failure (with diagnostic output on stderr)
#   - print a "=== E2E ... PASSED ===" footer when successful
#
# Usage:
#   ./e2e/run_all.sh
#
# Prereqs:
#   - cluacov has been built into the local tree
#     (`luarocks --lua-version=5.5 make cluacov-dev-1.rockspec --tree=.`)
#   - lua/luarocks visible in PATH
#

set -u

# Resolve the directory containing THIS script (works regardless of cwd).
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

cd "$repo_root"

# Detect the Lua version from the `lua` binary on PATH so the script
# works for 5.4, 5.5 and any future version without hardcoding.
lua_ver="$(lua -e 'io.write(string.match(_VERSION, "%d+%.%d+"))')"

# Wire up local rocks tree so `require("cluacov.*")` finds the built
# .so files. Idempotent: safe to run inside an already-set-up shell.
# `--tree=.` prepends ./share/lua/<ver> and ./lib/lua/<ver> so that
# `luarocks make --tree=.` artifacts win over any older globally
# installed cluacov rock.
eval "$(luarocks --lua-version="$lua_ver" --tree=. path)"

# Make local-tree .so files take priority (luarocks make --tree=. puts
# them in ./lib/lua/$lua_ver/cluacov/ which the eval above already
# covers, but we also pick up the legacy ./cluacov/*.so layout if present).
export LUA_CPATH="./?.so;./cluacov/?.so;${LUA_CPATH:-};;"

scripts=(
   "e2e_branch_coverage.lua"
   "e2e_function_coverage.lua"
   "e2e_line_hook.lua"
   "e2e_runner_shutdown.lua"
   "e2e_tick_mode.lua"
   "e2e_coroutine.lua"
   "e2e_multi_source.lua"
)

pass=0
fail=0
failed_scripts=()

for script in "${scripts[@]}"; do
   path="$script_dir/$script"
   if [[ ! -f "$path" ]]; then
      echo "SKIP: $script (not found)"
      continue
   fi

   echo
   echo "============================================================"
   echo " RUN: $script"
   echo "============================================================"

   if lua "$path"; then
      echo ">>> $script: PASS"
      pass=$((pass + 1))
   else
      code=$?
      echo ">>> $script: FAIL (exit=$code)"
      fail=$((fail + 1))
      failed_scripts+=("$script")
   fi
done

echo
echo "============================================================"
echo " SUMMARY: $pass passed, $fail failed (of $((pass + fail)) total)"
echo "============================================================"

# Generate a top-level HTML index page that links to every per-scenario
# HTML coverage report under e2e/output/. Convenient for local dev:
# `open e2e/output/index.html` opens a single jumping-off page.
output_dir="$repo_root/e2e/output"
index_html="$output_dir/index.html"

if [[ -d "$output_dir" ]]; then
   echo
   echo "Generating top-level index: $index_html"

   # Collect ONLY the top-level index.html of each scenario:
   #   output/html/index.html                       (branch_coverage)
   #   output/runner_shutdown/html/index.html       (runner_shutdown)
   #   output/tick_branch/html/index.html           (tick_branch)
   #   output/multi_source/html/index.html          (multi_source)
   # genhtml also creates nested per-directory index.html files; we
   # don't list those here — users can drill down from the scenario
   # report's own UI.
   declare -A seen
   reports=()
   while IFS= read -r line; do
      # Dedupe: keep only the shortest path under each "html/" root.
      dir="$(dirname "$line")"
      root="${dir%%/html*}/html"
      if [[ -z "${seen[$root]:-}" ]] && [[ -f "$root/index.html" ]]; then
         seen[$root]=1
         reports+=("$root/index.html")
      fi
   done < <(find "$output_dir" -mindepth 2 -name "index.html" 2>/dev/null | sort)

   {
      echo "<!DOCTYPE html>"
      echo "<html lang=\"en\"><head><meta charset=\"UTF-8\">"
      echo "<title>cluacov E2E coverage reports</title>"
      echo "<style>"
      echo "  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#222;}"
      echo "  h1{border-bottom:2px solid #4a7;padding-bottom:8px;}"
      echo "  ul{list-style:none;padding:0;}"
      echo "  li{margin:12px 0;padding:12px 16px;background:#f6f8fa;border-radius:6px;border-left:4px solid #4a7;}"
      echo "  a{color:#0366d6;text-decoration:none;font-weight:600;font-size:1.05em;}"
      echo "  a:hover{text-decoration:underline;}"
      echo "  .desc{color:#666;font-size:0.9em;margin-top:4px;}"
      echo "  .meta{color:#888;font-size:0.85em;margin-top:20px;}"
      echo "</style></head><body>"
      echo "<h1>cluacov E2E coverage reports</h1>"
      echo "<p>Generated by <code>e2e/run_all.sh</code> on $(date '+%Y-%m-%d %H:%M:%S').</p>"
      echo "<p>$pass / $((pass + fail)) e2e scripts passed.</p>"
      if [[ ${#reports[@]} -eq 0 ]]; then
         echo "<p><em>No HTML reports found. Run individual e2e scripts to generate them.</em></p>"
      else
         echo "<ul>"
         for r in "${reports[@]}"; do
            rel="${r#$output_dir/}"
            # Friendly label: derive scenario from the path prefix.
            case "$rel" in
               html/index.html)
                  label="Branch coverage (per-PC)"
                  desc="PC-mode + branchcov full pipeline — produced by <code>e2e_branch_coverage.lua</code>"
                  ;;
               runner_shutdown/html/index.html)
                  label="Runner shutdown (__gc finalizer path)"
                  desc="Regression report for the __gc shutdown SIGSEGV bug — produced by <code>e2e_runner_shutdown.lua</code>"
                  ;;
               tick_branch/html/index.html)
                  label="Tick-mode branch coverage"
                  desc="Tick save_stats + per-PC branchcov + LCOV/genhtml — produced by <code>e2e_tick_mode.lua</code>"
                  ;;
               multi_source/html/index.html)
                  label="Multi-source aggregation"
                  desc="8 distinct module sources, per-source line attribution — produced by <code>e2e_multi_source.lua</code>"
                  ;;
               *)
                  label="$rel"
                  desc=""
                  ;;
            esac
            echo "  <li><a href=\"$rel\">$label</a><div class=\"desc\">$desc</div></li>"
         done
         echo "</ul>"
      fi
      echo "<p class=\"meta\">cluacov is a Lua coverage tool. Source: <a href=\"https://github.com/yeshan333/cluacov\">github.com/yeshan333/cluacov</a></p>"
      echo "</body></html>"
   } > "$index_html"

   echo "  -> ${#reports[@]} report(s) linked. Open with: open \"$index_html\""
fi

if [[ $fail -gt 0 ]]; then
   echo "Failed scripts:"
   for s in "${failed_scripts[@]}"; do
      echo "  - $s"
   done
   exit 1
fi

exit 0
